// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type Mutation struct {
}

type NutritionalValue struct {
	ID                 string  `json:"id"`
	Unit               string  `json:"unit"`
	EnergyValueKcal    float64 `json:"energyValueKcal"`
	Fat                float64 `json:"fat"`
	SaturatedFat       float64 `json:"saturatedFat"`
	Carbohydrate       float64 `json:"carbohydrate"`
	CarbohydrateSugars float64 `json:"carbohydrateSugars"`
	Fibre              float64 `json:"fibre"`
	Protein            float64 `json:"protein"`
	Salt               float64 `json:"salt"`
}

type NutritionalValueInput struct {
	Unit               string  `json:"unit"`
	EnergyValueKcal    float64 `json:"energyValueKcal"`
	Fat                float64 `json:"fat"`
	SaturatedFat       float64 `json:"saturatedFat"`
	Carbohydrate       float64 `json:"carbohydrate"`
	CarbohydrateSugars float64 `json:"carbohydrateSugars"`
	Fibre              float64 `json:"fibre"`
	Protein            float64 `json:"protein"`
	Salt               float64 `json:"salt"`
}

type Product struct {
	ID   string `json:"id"`
	Name string `json:"name"`
}

type ProductAggregate struct {
	Name      string     `json:"name"`
	Varieties []*Variety `json:"varieties"`
}

type ProductAggregateInput struct {
	Name             string                 `json:"name"`
	VarietyName      string                 `json:"varietyName"`
	NutritionalValue *NutritionalValueInput `json:"nutritionalValue,omitempty"`
	Purchase         *PurchaseInput         `json:"purchase,omitempty"`
}

type Purchase struct {
	ID       string  `json:"id"`
	Date     string  `json:"date"`
	Quantity float64 `json:"quantity"`
	Price    float64 `json:"price"`
	Retailer string  `json:"retailer"`
	Unit     string  `json:"unit"`
	Notes    string  `json:"notes"`
}

type PurchaseInput struct {
	Date     string  `json:"date"`
	Quantity float64 `json:"quantity"`
	Price    float64 `json:"price"`
	Retailer string  `json:"retailer"`
	Unit     string  `json:"unit"`
	Notes    string  `json:"notes"`
}

type Query struct {
}

type Variety struct {
	VarietyName      string            `json:"varietyName"`
	NutritionalValue *NutritionalValue `json:"nutritionalValue,omitempty"`
	Purchases        []*Purchase       `json:"purchases"`
}
